# Generated by Django 4.1.4 on 2023-02-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
