# Generated by Django 4.1.4 on 2023-01-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("summary", models.TextField(max_length=1000)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("director", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="avatar"),
                ),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="Movies.categories",
                    ),
                ),
            ],
        ),
    ]
