# Generated by Django 4.1.4 on 2023-01-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0002_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
