# Generated by Django 4.1.4 on 2023-02-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0004_remove_movies_category_movies_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="poster"),
        ),
    ]
