# Generated by Django 4.1.4 on 2023-02-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Reviews", "0002_review_date"),
        ("Movies", "0005_alter_movies_poster"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="categories",
            new_name="category",
        ),
        migrations.RenameModel(
            old_name="movies",
            new_name="movie",
        ),
    ]
