# Generated by Django 4.1.4 on 2023-02-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0006_rename_categories_category_rename_movies_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
