# Generated by Django 4.1.4 on 2023-02-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0007_movie_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
