# Generated by Django 4.1.4 on 2023-02-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0008_alter_movie_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="category",
        ),
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="Movies.category",
            ),
        ),
    ]
