# Generated by Django 4.1.4 on 2023-02-05 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Movies", "0009_remove_movie_category_movie_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="Movies.category",
            ),
        ),
    ]
